language: rust
before_install:
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      fi
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
        - COVERAGE=1
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
    - |
      if [ "$COVERAGE" = "1" ] && [ -z "$TRAVIS_TAG" ]
      then
        export CARGO_INCREMENTAL=0;
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off";
        export BUILD_MODULES="core"
      else
        export BUILD_MODULES="."
      fi
    - if [ "$TRAVIS_TAG" ]; then export CARGO_OPTIONS="${CARGO_OPTIONS} --release"; fi
    - for MOD in $BUILD_MODULES; do cd "$MOD"; cargo build --verbose $CARGO_OPTIONS; cargo test --verbose $CARGO_OPTIONS; cd -; done
    - |
      if [ "$COVERAGE" = "1" ] && [ -z "$TRAVIS_TAG" ]; then
        zip -0 ccov.zip `find . -name "rhombus*.gc*" -print`;
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
      fi
